### ISSUE TITLE
Storyblok doesnt work in +page.server.js

### ISSUE THREAD

**Issue by mattpilott** [storyblok/storyblok-svelte#472]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Sotryblok for svelte currently only works in hybrid routes `+page.js` but it would be nice to have the option to use `+page.server.js` too. In projects where other API's or server side logic needs to happen in the load function it can be tricky to get things to work as client and server behaviour differs.

Currently when you try to use `+page.server.js` you get an error about use get:
```
TypeError: Cannot read properties of undefined (reading 'get')
```

---

## Expected Behavior

it should work in either hybrid or server page routes

## Current Behavior

only works in hybrid routes

## Steps to Reproduce

1. Have a working +page.js file 
2. Rename to +page.server.js
3. Get error `TypeError: Cannot read properties of undefined (reading 'get')`

**Comment by josefineschaefer** [comment]
Thank you @mattpilott we will investigate. 

Did you move the code from `layout.js` to `layout.server.js`? Because in the page we are reusing the Storyblok instance, created it in the layout and then share it from the layout to the page as parent.

**Comment by mattpilott** [comment]
Yup so this is the error i get if everything is set to .server and also a screen of my routes folder, happy to try any ideas you have and report back!
```bash
{
  message: 'Data returned from `load` while rendering /[[lang=lang]]/[...page] is not serializable: Cannot stringify arbitrary non-POJOs (data.storyblokApi)',
  code: 'UNKNOWN',
  env: undefined
}
```
<img width="232" alt="Screenshot 2023-04-19 at 11 30 54 am" src="https://user-images.githubusercontent.com/2401925/233048186-98e3f7ca-9aaf-4b8b-a605-7aa868bf03cc.png">

**Comment by mattpilott** [comment]
@josefineschaefer any thoughts on this one?

**Comment by josefineschaefer** [comment]
My amazing colleague @roberto-butti found a solution to your problem and will share it tomorrow :) Thank you for your patience.

**Comment by roberto-butti** [comment]
Hi @mattpilott , I'm using the svelte Storyblok sdk on server side.
I don't know if the example i made, it fits your needs, but you can take a look if you want.
I have this example, running a pure server-side logic (I also disabled csr in the /serverside/ route example): https://github.com/roberto-butti/my-storyblok-sveltekit-example#server-side

The route folder is serverside: https://github.com/roberto-butti/my-storyblok-sveltekit-example/tree/main/src/routes/serverside


The issue in the ultimate tutorial (that doesn't use the *.server.js files) is that the storyblok instance is created in the `load` function of the `+layout.js` file, and then, the object is shared to the `+page.js` `load` function via "parent" approach: https://kit.svelte.dev/docs/load#using-parent-data .
The parent approach is great for sharing simple objects (plain objects) across layout/page.
In this case ( the server approach with the sharing the storyblok object via the parent approach ), it raises an exception (because it is not a plain object).

**Comment by mattpilott** [comment]
@roberto-butti that sounds like the missing piece of information i needed and makes complete sense. I'll create a new storyblok instance in each server route and then it should all work, will test and close if it works out

**Comment by roberto-butti** [comment]
@mattpilott  In the previous comment, I told you I skipped the CSR part in a pure server-side solution.
Performing some fine-tuning with my example, I have a complete working example:
https://github.com/roberto-butti/my-storyblok-sveltekit-example/tree/main/src/routes/serverside

**Comment by mattpilott** [comment]
@roberto-butti i have been working on making my project server-side only so i dont leak my access token and have run into a hurdle with renderRichText

How can i run the renderRichText function in a component when storyblok is initialised server-side?

**Comment by roberto-butti** [comment]
Hello @mattpilott, in our last workshop, I made an example, I just pushed the example for using server-side routes and rich text.
You can take a look at it here:
https://github.com/roberto-butti/sveltekit-storyblok-workshop/tree/main/src/routes/server/%5Bslug%5D

The component is server/client agnostic: 
https://github.com/roberto-butti/sveltekit-storyblok-workshop/blob/main/src/lib/components/Textblok.svelte

**Comment by mattpilott** [comment]
@roberto-butti its been awhile im attempting this move once more and still cannot implement a serverside approach with renderrichtext. I get this `Please initialize the Storyblok SDK before calling the renderRichText function`

**Comment by mattpilott** [comment]
I may be able to temporarily skirt the issue by using the rich text resolver from the storyblok client js

https://github.com/storyblok/storyblok-js-client?tab=readme-ov-file#using-the-richtextresolver-separately
